### ISSUE TITLE
(Suggestion) TitleID Change

### ISSUE THREAD

**Issue by Smoker1** [bythos14/sm64-vita#2]
Suggest changing the TitleID from SM6400001, to PCSE64001. Reasons......

1 - VitaCheat/Final Cheat is unable to be used with Homebrew. Was informed that it will only work with TitleIDs that match PCSx##### (x=A-H). This way, Users can create Codes for Cheats, and if possible, make Mods.

2 - Since there are a number of N64 Games that have been Decrypted and can be Ported, with this TitleID System, any other Games can just be PCSE640##. The 64 being of N64 Games, with the last 3 Numbers being Released Number, in order.

**Comment by bythos14** [comment]
See commit e9c4b2b. This repository will be archived and will most likely receive no updates in the future.
